Updated docs
medrunner-services/api-client-ts pull request #111
Opened 2024-12-18 06:08 UTC by ElliotThiebaut

2024-12-18 06:34 UTC, charliefoxtwo requested changes

2024-12-18 06:34 UTC, charliefoxtwo commented on docs/reference/websockets-events.md
> +Triggers when a chat message is added to an emergency where the user participates.
Copypasta

2024-12-19 02:51 UTC, ElliotThiebaut commented on docs/reference/websockets-events.md
> +Triggers when a chat message is added to an emergency where the user participates.
Fixed!

2024-12-19 03:16 UTC, charliefoxtwo approved these changes

2024-12-19 03:17 UTC, merged